/**
 * Cross-platform scheduling for periodic `collect --then-ingest`. Node can time work (see `watch`)
 * but can't survive a reboot on its own, so this registers the job with the OS scheduler:
 *   - Linux   → systemd user timer (+ linger, so it runs while logged out)
 *   - macOS   → launchd LaunchAgent (StartCalendarInterval)
 *   - Windows → Task Scheduler (schtasks), one daily task per configured hour
 *
 * The absolute `node` binary (process.execPath) and CLI entry path are baked into every unit/plist/
 * task, because schedulers don't inherit the interactive shell's PATH (the mise problem, generalized).
 * The unit/plist/command text is generated by the pure functions below (unit-tested); runSchedule
 * wraps them with the OS commands.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { join } from "node:path";
import { findRepoRoot, resolveDataDir } from "./paths.js";

export const DEFAULT_HOURS = [9, 13, 17, 21];
const SYSTEMD_TIMER = "agent-lens-collect.timer";
const SYSTEMD_SERVICE = "agent-lens-collect.service";
const LAUNCHD_LABEL = "org.agent-lens.collect";
const WINDOWS_TASK_PREFIX = "AgentLens\\Collect";

export interface ScheduleParams {
  /** Absolute path to the CLI entry (the bundled agent-lens.js). */
  cliEntry: string;
  /** Hours (0–23) to run at. Default: DEFAULT_HOURS. */
  hours?: number[];
  /** Absolute node binary. Default: process.execPath. */
  node?: string;
}

export function parseHours(spec: string | undefined): number[] {
  if (!spec) return DEFAULT_HOURS;
  const hours = spec
    .split(",")
    .map((s) => Number.parseInt(s.trim(), 10))
    .filter((n) => Number.isInteger(n) && n >= 0 && n <= 23);
  if (!hours.length) throw new Error(`invalid hours '${spec}' (expected comma-separated 0-23, e.g. 9,13,17,21)`);
  return [...new Set(hours)].sort((a, b) => a - b);
}

// ---- pure generators (unit-tested) --------------------------------------------------------------

/** systemd `OnCalendar` hour list, e.g. [9,13] → "09,13:00". */
export function onCalendarHours(hours: number[]): string {
  return hours.map((h) => String(h).padStart(2, "0")).join(",") + ":00";
}

export function systemdService(node: string, cli: string): string {
  return `[Unit]
Description=Agent Lens — collect + ingest Claude Code session traces

[Service]
Type=oneshot
# Absolute node + CLI paths: systemd user services don't inherit the interactive PATH.
ExecStart=${node} ${cli} collect --then-ingest
Nice=10
IOSchedulingClass=idle
`;
}

export function systemdTimer(hours: number[]): string {
  return `[Unit]
Description=Agent Lens — periodic Claude Code trace collection

[Timer]
# A few times a day. Persistent catches runs missed while the machine was off.
OnCalendar=*-*-* ${onCalendarHours(hours)}
Persistent=true
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
`;
}

export function launchdPlist(node: string, cli: string, hours: number[], logPath: string): string {
  const cal = hours
    .map((h) => `    <dict><key>Hour</key><integer>${h}</integer><key>Minute</key><integer>0</integer></dict>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${node}</string>
    <string>${cli}</string>
    <string>collect</string>
    <string>--then-ingest</string>
  </array>
  <key>StartCalendarInterval</key>
  <array>
${cal}
  </array>
  <key>StandardOutPath</key><string>${logPath}</string>
  <key>StandardErrorPath</key><string>${logPath}</string>
</dict>
</plist>
`;
}

// ---- OS helpers ---------------------------------------------------------------------------------

function sh(cmd: string, args: string[], quiet = false): boolean {
  const r = spawnSync(cmd, args, { stdio: quiet ? "ignore" : "inherit", encoding: "utf8" });
  return r.status === 0;
}

function have(cmd: string): boolean {
  const r = spawnSync(cmd, ["--version"], { stdio: "ignore" });
  return r.status === 0 || r.error === undefined;
}

function systemdUnitDir(): string {
  return join(process.env.XDG_CONFIG_HOME || join(homedir(), ".config"), "systemd", "user");
}

// ---- Linux (systemd user) -----------------------------------------------------------------------

function linuxInstall(node: string, cli: string, hours: number[]): void {
  if (!have("systemctl")) {
    console.error("agent-lens schedule: systemctl not found — is this a systemd system?");
    process.exitCode = 1;
    return;
  }
  const dir = systemdUnitDir();
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, SYSTEMD_SERVICE), systemdService(node, cli));
  writeFileSync(join(dir, SYSTEMD_TIMER), systemdTimer(hours));
  sh("systemctl", ["--user", "daemon-reload"]);
  sh("systemctl", ["--user", "enable", "--now", SYSTEMD_TIMER]);
  // Run while logged out (best-effort).
  if (have("loginctl") && !sh("loginctl", ["enable-linger", process.env.USER || ""], true)) {
    console.log(`agent-lens: could not enable linger automatically; run: sudo loginctl enable-linger ${process.env.USER}`);
  }
  console.log(`agent-lens schedule: installed systemd user timer (${onCalendarHours(hours)})`);
  sh("systemctl", ["--user", "list-timers", SYSTEMD_TIMER, "--no-pager"]);
}

function linuxUninstall(): void {
  if (!have("systemctl")) return;
  sh("systemctl", ["--user", "disable", "--now", SYSTEMD_TIMER], true);
  const dir = systemdUnitDir();
  for (const u of [SYSTEMD_TIMER, SYSTEMD_SERVICE]) rmSync(join(dir, u), { force: true });
  sh("systemctl", ["--user", "daemon-reload"]);
  sh("systemctl", ["--user", "reset-failed", SYSTEMD_SERVICE], true);
  console.log("agent-lens schedule: uninstalled systemd user timer (archive untouched)");
}

function linuxStatus(): void {
  if (!have("systemctl")) return;
  sh("systemctl", ["--user", "list-timers", SYSTEMD_TIMER, "--no-pager"]);
}

// ---- macOS (launchd) ----------------------------------------------------------------------------

function launchdPlistPath(): string {
  return join(homedir(), "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

function macInstall(node: string, cli: string, hours: number[]): void {
  const plist = launchdPlistPath();
  mkdirSync(join(homedir(), "Library", "LaunchAgents"), { recursive: true });
  const logPath = join(resolveDataDir(findRepoRoot()), "schedule.log");
  writeFileSync(plist, launchdPlist(node, cli, hours, logPath));
  const uid = typeof process.getuid === "function" ? process.getuid() : 0;
  // Prefer the modern bootstrap API; fall back to legacy load -w.
  if (!sh("launchctl", ["bootstrap", `gui/${uid}`, plist], true)) sh("launchctl", ["load", "-w", plist]);
  console.log(`agent-lens schedule: installed launchd agent ${LAUNCHD_LABEL} (hours ${hours.join(",")})`);
}

function macUninstall(): void {
  const plist = launchdPlistPath();
  const uid = typeof process.getuid === "function" ? process.getuid() : 0;
  if (!sh("launchctl", ["bootout", `gui/${uid}/${LAUNCHD_LABEL}`], true)) sh("launchctl", ["unload", "-w", plist], true);
  rmSync(plist, { force: true });
  console.log("agent-lens schedule: uninstalled launchd agent (archive untouched)");
}

function macStatus(): void {
  const uid = typeof process.getuid === "function" ? process.getuid() : 0;
  sh("launchctl", ["print", `gui/${uid}/${LAUNCHD_LABEL}`]);
}

// ---- Windows (schtasks) -------------------------------------------------------------------------

function winTaskName(hour: number): string {
  return `${WINDOWS_TASK_PREFIX}_${String(hour).padStart(2, "0")}`;
}

function windowsInstall(node: string, cli: string, hours: number[]): void {
  const tr = `"${node}" "${cli}" collect --then-ingest`;
  for (const h of hours) {
    sh("schtasks", ["/Create", "/F", "/TN", winTaskName(h), "/TR", tr, "/SC", "DAILY", "/ST", `${String(h).padStart(2, "0")}:00`]);
  }
  console.log(`agent-lens schedule: installed ${hours.length} Windows task(s) (hours ${hours.join(",")})`);
}

function windowsUninstall(): void {
  // Delete every task under our prefix (we don't need to know the original hours).
  for (let h = 0; h < 24; h++) sh("schtasks", ["/Delete", "/F", "/TN", winTaskName(h)], true);
  console.log("agent-lens schedule: uninstalled Windows tasks (archive untouched)");
}

function windowsStatus(): void {
  sh("schtasks", ["/Query", "/FO", "LIST", "/TN", WINDOWS_TASK_PREFIX], true) ||
    console.log("agent-lens schedule: no Windows tasks found under " + WINDOWS_TASK_PREFIX);
}

// ---- dispatch -----------------------------------------------------------------------------------

export type ScheduleAction = "install" | "uninstall" | "status";

export function runSchedule(action: string, params: ScheduleParams): void {
  const node = params.node ?? process.execPath;
  const cli = params.cliEntry;
  const hours = params.hours ?? DEFAULT_HOURS;
  const plat = platform();
  const impl =
    plat === "linux"
      ? { install: () => linuxInstall(node, cli, hours), uninstall: linuxUninstall, status: linuxStatus }
      : plat === "darwin"
        ? { install: () => macInstall(node, cli, hours), uninstall: macUninstall, status: macStatus }
        : plat === "win32"
          ? { install: () => windowsInstall(node, cli, hours), uninstall: windowsUninstall, status: windowsStatus }
          : null;
  if (!impl) {
    console.error(`agent-lens schedule: unsupported platform '${plat}'`);
    process.exitCode = 1;
    return;
  }
  if (action === "install") impl.install();
  else if (action === "uninstall") impl.uninstall();
  else if (action === "status") impl.status();
  else {
    console.error(`agent-lens schedule: unknown action '${action}' (use: install | uninstall | status)`);
    process.exitCode = 1;
  }
}
