/**
 * Cross-platform OS-service integration for `agent-lens service`. Two targets:
 *   - collector → a *periodic* `collect --then-ingest` job (Node can time work via `watch`, but
 *     can't survive a reboot alone, so we register it with the OS scheduler)
 *   - server    → the *long-running* web UI + read-only API daemon (`serve`)
 *
 * Per platform:
 *   - Linux   → systemd user units (collector: oneshot service + timer; server: Type=simple + Restart) + linger
 *   - macOS   → launchd LaunchAgents (collector: StartCalendarInterval; server: KeepAlive)
 *   - Windows → Task Scheduler (collector: one DAILY task per hour; server: ONLOGON task)
 *
 * The absolute `node` binary (process.execPath) and CLI entry path are baked into every unit/plist/
 * task, because schedulers don't inherit the interactive shell's PATH (the mise problem, generalized).
 * The unit/plist/command text is generated by the pure functions below (unit-tested); runService
 * wraps them with the OS commands.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir, platform, userInfo } from "node:os";
import { join } from "node:path";
import { findRepoRoot, resolveDataDir } from "./paths.js";
import { resolveServerConfig } from "./config.js";

export const DEFAULT_HOURS = [9, 13, 17, 21];

/**
 * The login name for `loginctl enable-linger`. Asks the OS (passwd entry) rather than reading $USER:
 * schedulers and `env -i` don't set it, which is exactly when this runs, and under sudo it names the
 * invoking user while the units belong to the effective one. Falls back to the env only if the
 * passwd lookup fails (rare — a uid with no entry, seen in some containers); "" means "unknown", and
 * callers skip linger rather than shelling out with an empty argument.
 */
export function currentUser(): string {
  try {
    return userInfo().username;
  } catch {
    return process.env.USER || process.env.LOGNAME || "";
  }
}

const SYSTEMD_COLLECTOR_TIMER = "agent-lens-collect.timer";
const SYSTEMD_COLLECTOR_SERVICE = "agent-lens-collect.service";
const SYSTEMD_SERVER_SERVICE = "agent-lens-server.service";
const LAUNCHD_COLLECTOR_LABEL = "org.agent-lens.collect";
const LAUNCHD_SERVER_LABEL = "org.agent-lens.server";
const WINDOWS_COLLECTOR_PREFIX = "AgentLens\\Collect";
const WINDOWS_SERVER_TASK = "AgentLens\\Server";

export type ServiceTarget = "collector" | "server";
export type ServiceAction = "install" | "uninstall" | "status";

export interface ServiceParams {
  /** Absolute path to the CLI entry (the bundled agent-lens.js). */
  cliEntry: string;
  /** Which OS integrations to act on. */
  targets: ServiceTarget[];
  /** Hours (0–23) the collector runs at. Default: DEFAULT_HOURS. */
  hours?: number[];
  /** Absolute node binary. Default: process.execPath. */
  node?: string;
}

/** Parse the CLI target arg: undefined/"all" → both; "collector"/"server" → that one; else throw. */
export function parseTargets(spec: string | undefined): ServiceTarget[] {
  if (!spec || spec === "all") return ["collector", "server"];
  if (spec === "collector" || spec === "server") return [spec];
  throw new Error(`invalid target '${spec}' (expected: collector | server | all)`);
}

export function parseHours(spec: string | undefined): number[] {
  if (!spec) return DEFAULT_HOURS;
  const hours = spec
    .split(",")
    .map((s) => Number.parseInt(s.trim(), 10))
    .filter((n) => Number.isInteger(n) && n >= 0 && n <= 23);
  if (!hours.length) throw new Error(`invalid hours '${spec}' (expected comma-separated 0-23, e.g. 9,13,17,21)`);
  return [...new Set(hours)].sort((a, b) => a - b);
}

/**
 * Effective port/host to bake into the server unit. Resolves via the shared config precedence
 * (env > config file > default) and bakes any value the user explicitly set — from the shell env OR
 * `server.{port,host}` in agent-lens.config.json — so the scheduled server matches what they run
 * interactively (schedulers don't inherit the shell env, hence the baking). Defaults stay unbaked so
 * a future default change still applies to already-installed units.
 */
function serverEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  const { port, host, portOrigin, hostOrigin } = resolveServerConfig();
  if (portOrigin !== "default") env.AGENT_LENS_PORT = String(port);
  if (hostOrigin !== "default") env.AGENT_LENS_HOST = host;
  return env;
}

// ---- pure generators (unit-tested) --------------------------------------------------------------

/** systemd `OnCalendar` hour list, e.g. [9,13] → "09,13:00". */
export function onCalendarHours(hours: number[]): string {
  return hours.map((h) => String(h).padStart(2, "0")).join(",") + ":00";
}

/** Collector: oneshot unit that runs one `collect --then-ingest` pass (driven by the timer). */
export function systemdCollectorService(node: string, cli: string): string {
  return `[Unit]
Description=Agent Lens — collect + ingest Claude Code session traces

[Service]
Type=oneshot
# Absolute node + CLI paths: systemd user services don't inherit the interactive PATH.
ExecStart=${node} ${cli} collect --then-ingest
Nice=10
IOSchedulingClass=idle
`;
}

export function systemdCollectorTimer(hours: number[]): string {
  return `[Unit]
Description=Agent Lens — periodic Claude Code trace collection

[Timer]
# A few times a day. Persistent catches runs missed while the machine was off.
OnCalendar=*-*-* ${onCalendarHours(hours)}
Persistent=true
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
`;
}

/** Server: long-running daemon that runs `serve`, restarted on failure. */
export function systemdServerService(node: string, cli: string, env: Record<string, string> = {}): string {
  const envLines = Object.entries(env)
    .map(([k, v]) => `Environment=${k}=${v}\n`)
    .join("");
  return `[Unit]
Description=Agent Lens — local web UI + read-only API server
After=network.target

[Service]
Type=simple
# Absolute node + CLI paths: systemd user services don't inherit the interactive PATH.
ExecStart=${node} ${cli} serve
${envLines}# Long-running: always come back, including after a bare SIGTERM. systemd counts SIGTERM as a
# clean exit, so Restart=on-failure would leave the server dead after a stray "pkill -f ... serve"
# aimed at an ad-hoc test server — the unit's ExecStart matches that pattern too. Matches the
# launchd KeepAlive=true behaviour. An explicit "systemctl --user stop" still stops it for good.
Restart=always
RestartSec=5
Nice=10

[Install]
WantedBy=default.target
`;
}

export function launchdCollectorPlist(node: string, cli: string, hours: number[], logPath: string): string {
  const cal = hours
    .map((h) => `    <dict><key>Hour</key><integer>${h}</integer><key>Minute</key><integer>0</integer></dict>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LAUNCHD_COLLECTOR_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${node}</string>
    <string>${cli}</string>
    <string>collect</string>
    <string>--then-ingest</string>
  </array>
  <key>StartCalendarInterval</key>
  <array>
${cal}
  </array>
  <key>StandardOutPath</key><string>${logPath}</string>
  <key>StandardErrorPath</key><string>${logPath}</string>
</dict>
</plist>
`;
}

/** Server: launchd agent kept alive (relaunched if it exits) and started at load. */
export function launchdServerPlist(node: string, cli: string, logPath: string, env: Record<string, string> = {}): string {
  const envDict = Object.entries(env).length
    ? `  <key>EnvironmentVariables</key>\n  <dict>\n${Object.entries(env)
        .map(([k, v]) => `    <key>${k}</key><string>${v}</string>`)
        .join("\n")}\n  </dict>\n`
    : "";
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LAUNCHD_SERVER_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${node}</string>
    <string>${cli}</string>
    <string>serve</string>
  </array>
${envDict}  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${logPath}</string>
  <key>StandardErrorPath</key><string>${logPath}</string>
</dict>
</plist>
`;
}

// ---- OS helpers ---------------------------------------------------------------------------------

function sh(cmd: string, args: string[], quiet = false): boolean {
  const r = spawnSync(cmd, args, { stdio: quiet ? "ignore" : "inherit", encoding: "utf8" });
  return r.status === 0;
}

function have(cmd: string): boolean {
  const r = spawnSync(cmd, ["--version"], { stdio: "ignore" });
  return r.status === 0 || r.error === undefined;
}

function systemdUnitDir(): string {
  return join(process.env.XDG_CONFIG_HOME || join(homedir(), ".config"), "systemd", "user");
}

// ---- Linux (systemd user) -----------------------------------------------------------------------

function linuxInstall(targets: ServiceTarget[], node: string, cli: string, hours: number[]): void {
  if (!have("systemctl")) {
    console.error("agent-lens service: systemctl not found — is this a systemd system?");
    process.exitCode = 1;
    return;
  }
  const dir = systemdUnitDir();
  mkdirSync(dir, { recursive: true });
  if (targets.includes("collector")) {
    writeFileSync(join(dir, SYSTEMD_COLLECTOR_SERVICE), systemdCollectorService(node, cli));
    writeFileSync(join(dir, SYSTEMD_COLLECTOR_TIMER), systemdCollectorTimer(hours));
  }
  if (targets.includes("server")) {
    writeFileSync(join(dir, SYSTEMD_SERVER_SERVICE), systemdServerService(node, cli, serverEnv()));
  }
  sh("systemctl", ["--user", "daemon-reload"]);
  if (targets.includes("collector")) {
    sh("systemctl", ["--user", "enable", "--now", SYSTEMD_COLLECTOR_TIMER]);
    console.log(`agent-lens service: installed collector timer (${onCalendarHours(hours)})`);
    sh("systemctl", ["--user", "list-timers", SYSTEMD_COLLECTOR_TIMER, "--no-pager"]);
  }
  if (targets.includes("server")) {
    sh("systemctl", ["--user", "enable", "--now", SYSTEMD_SERVER_SERVICE]);
    console.log("agent-lens service: installed server daemon");
    sh("systemctl", ["--user", "status", SYSTEMD_SERVER_SERVICE, "--no-pager"]);
  }
  // Run while logged out (best-effort) — needed for both the timer and the daemon.
  const user = currentUser();
  if (user && have("loginctl") && !sh("loginctl", ["enable-linger", user], true)) {
    console.log(`agent-lens: could not enable linger automatically; run: sudo loginctl enable-linger ${user}`);
  }
}

function linuxUninstall(targets: ServiceTarget[]): void {
  if (!have("systemctl")) return;
  const dir = systemdUnitDir();
  if (targets.includes("collector")) {
    sh("systemctl", ["--user", "disable", "--now", SYSTEMD_COLLECTOR_TIMER], true);
    for (const u of [SYSTEMD_COLLECTOR_TIMER, SYSTEMD_COLLECTOR_SERVICE]) rmSync(join(dir, u), { force: true });
    sh("systemctl", ["--user", "reset-failed", SYSTEMD_COLLECTOR_SERVICE], true);
  }
  if (targets.includes("server")) {
    sh("systemctl", ["--user", "disable", "--now", SYSTEMD_SERVER_SERVICE], true);
    rmSync(join(dir, SYSTEMD_SERVER_SERVICE), { force: true });
    sh("systemctl", ["--user", "reset-failed", SYSTEMD_SERVER_SERVICE], true);
  }
  sh("systemctl", ["--user", "daemon-reload"]);
  console.log("agent-lens service: uninstalled (archive untouched)");
}

function linuxStatus(targets: ServiceTarget[]): void {
  if (!have("systemctl")) return;
  if (targets.includes("collector")) sh("systemctl", ["--user", "list-timers", SYSTEMD_COLLECTOR_TIMER, "--no-pager"]);
  if (targets.includes("server")) sh("systemctl", ["--user", "status", SYSTEMD_SERVER_SERVICE, "--no-pager"]);
}

// ---- macOS (launchd) ----------------------------------------------------------------------------

function launchdPlistPath(label: string): string {
  return join(homedir(), "Library", "LaunchAgents", `${label}.plist`);
}

function macBootstrap(plist: string): void {
  const uid = typeof process.getuid === "function" ? process.getuid() : 0;
  // Prefer the modern bootstrap API; fall back to legacy load -w.
  if (!sh("launchctl", ["bootstrap", `gui/${uid}`, plist], true)) sh("launchctl", ["load", "-w", plist]);
}

function macBootout(label: string, plist: string): void {
  const uid = typeof process.getuid === "function" ? process.getuid() : 0;
  if (!sh("launchctl", ["bootout", `gui/${uid}/${label}`], true)) sh("launchctl", ["unload", "-w", plist], true);
  rmSync(plist, { force: true });
}

function macInstall(targets: ServiceTarget[], node: string, cli: string, hours: number[]): void {
  const agents = join(homedir(), "Library", "LaunchAgents");
  mkdirSync(agents, { recursive: true });
  const dataDir = resolveDataDir(findRepoRoot());
  if (targets.includes("collector")) {
    const plist = launchdPlistPath(LAUNCHD_COLLECTOR_LABEL);
    writeFileSync(plist, launchdCollectorPlist(node, cli, hours, join(dataDir, "schedule.log")));
    macBootstrap(plist);
    console.log(`agent-lens service: installed collector agent ${LAUNCHD_COLLECTOR_LABEL} (hours ${hours.join(",")})`);
  }
  if (targets.includes("server")) {
    const plist = launchdPlistPath(LAUNCHD_SERVER_LABEL);
    writeFileSync(plist, launchdServerPlist(node, cli, join(dataDir, "server.log"), serverEnv()));
    macBootstrap(plist);
    console.log(`agent-lens service: installed server agent ${LAUNCHD_SERVER_LABEL}`);
  }
}

function macUninstall(targets: ServiceTarget[]): void {
  if (targets.includes("collector")) macBootout(LAUNCHD_COLLECTOR_LABEL, launchdPlistPath(LAUNCHD_COLLECTOR_LABEL));
  if (targets.includes("server")) macBootout(LAUNCHD_SERVER_LABEL, launchdPlistPath(LAUNCHD_SERVER_LABEL));
  console.log("agent-lens service: uninstalled (archive untouched)");
}

function macStatus(targets: ServiceTarget[]): void {
  const uid = typeof process.getuid === "function" ? process.getuid() : 0;
  if (targets.includes("collector")) sh("launchctl", ["print", `gui/${uid}/${LAUNCHD_COLLECTOR_LABEL}`]);
  if (targets.includes("server")) sh("launchctl", ["print", `gui/${uid}/${LAUNCHD_SERVER_LABEL}`]);
}

// ---- Windows (schtasks) -------------------------------------------------------------------------

function winCollectorTaskName(hour: number): string {
  return `${WINDOWS_COLLECTOR_PREFIX}_${String(hour).padStart(2, "0")}`;
}

function windowsInstall(targets: ServiceTarget[], node: string, cli: string, hours: number[]): void {
  if (targets.includes("collector")) {
    const tr = `"${node}" "${cli}" collect --then-ingest`;
    for (const h of hours) {
      sh("schtasks", ["/Create", "/F", "/TN", winCollectorTaskName(h), "/TR", tr, "/SC", "DAILY", "/ST", `${String(h).padStart(2, "0")}:00`]);
    }
    console.log(`agent-lens service: installed ${hours.length} collector task(s) (hours ${hours.join(",")})`);
  }
  if (targets.includes("server")) {
    // ONLOGON runs in the user session, so the per-user data dir (%LOCALAPPDATA%) resolves.
    // Note: schtasks has no crash-restart (systemd/launchd do); a crashed server returns on next logon.
    const tr = `"${node}" "${cli}" serve`;
    sh("schtasks", ["/Create", "/F", "/TN", WINDOWS_SERVER_TASK, "/TR", tr, "/SC", "ONLOGON", "/RL", "LIMITED"]);
    console.log("agent-lens service: installed server task (starts at logon)");
  }
}

function windowsUninstall(targets: ServiceTarget[]): void {
  if (targets.includes("collector")) {
    // Delete every task under our prefix (we don't need to know the original hours).
    for (let h = 0; h < 24; h++) sh("schtasks", ["/Delete", "/F", "/TN", winCollectorTaskName(h)], true);
  }
  if (targets.includes("server")) sh("schtasks", ["/Delete", "/F", "/TN", WINDOWS_SERVER_TASK], true);
  console.log("agent-lens service: uninstalled (archive untouched)");
}

function windowsStatus(targets: ServiceTarget[]): void {
  if (targets.includes("collector")) {
    sh("schtasks", ["/Query", "/FO", "LIST", "/TN", WINDOWS_COLLECTOR_PREFIX], true) ||
      console.log("agent-lens service: no collector tasks found under " + WINDOWS_COLLECTOR_PREFIX);
  }
  if (targets.includes("server")) {
    sh("schtasks", ["/Query", "/FO", "LIST", "/TN", WINDOWS_SERVER_TASK], true) ||
      console.log("agent-lens service: no server task found (" + WINDOWS_SERVER_TASK + ")");
  }
}

// ---- dispatch -----------------------------------------------------------------------------------

export function runService(action: string, params: ServiceParams): void {
  const node = params.node ?? process.execPath;
  const cli = params.cliEntry;
  const hours = params.hours ?? DEFAULT_HOURS;
  const targets = params.targets;
  const plat = platform();
  const impl =
    plat === "linux"
      ? {
          install: () => linuxInstall(targets, node, cli, hours),
          uninstall: () => linuxUninstall(targets),
          status: () => linuxStatus(targets),
        }
      : plat === "darwin"
        ? {
            install: () => macInstall(targets, node, cli, hours),
            uninstall: () => macUninstall(targets),
            status: () => macStatus(targets),
          }
        : plat === "win32"
          ? {
              install: () => windowsInstall(targets, node, cli, hours),
              uninstall: () => windowsUninstall(targets),
              status: () => windowsStatus(targets),
            }
          : null;
  if (!impl) {
    console.error(`agent-lens service: unsupported platform '${plat}'`);
    process.exitCode = 1;
    return;
  }
  if (action === "install") impl.install();
  else if (action === "uninstall") impl.uninstall();
  else if (action === "status") impl.status();
  else {
    console.error(`agent-lens service: unknown action '${action}' (use: install | uninstall | status)`);
    process.exitCode = 1;
  }
}
